### ISSUE TITLE
無標音版本的台語字型？

### ISSUE THREAD

**Issue by whyjz** [ButTaiwan/taigivs#1]
@ButTaiwan 您好：

小弟目前正在為「[萌台語輸入法](https://github.com/whyjz/rime-moetaigi)」專案尋找合適的台語字型。這個字型需要包括臺語注音符號與幾乎所有的臺語外字，並且符合繁體漢字的台灣規範。然而我沒想到我知道的台語字型皆不符合此要求（細節可參閱whyjz/rime-moetaigi#5）。考量到字咍台語字型系列是最接近我尋找的目標，不知您有沒有計畫做完全無標音版本的台語字型，或是可能已經做好了，只是我沒有找到而已？

謝謝！

**Comment by ButTaiwan** [comment]
隨字型下載的zip檔裡的授權文件txt，有標註所有來源字型的專案網址。

源系列的也都是我的作品。

**Comment by ButTaiwan** [comment]
https://github.com/ButTaiwan/taigivs/blob/main/outputs/LICENSE-Gen.txt

**Comment by whyjz** [comment]
看來源系列字型就是我在尋找的目標，非常感謝指引！！
